### ISSUE TITLE
Authentication doesn't work 

### ISSUE THREAD

**Issue by valerijko** [jasonjoh/o365-vcftool#1]
I have cloned the project, replaced application id and application secret with data for my app, and i'm getting following errors on the first authentication step (when trying to get token):
error=unauthorized_client&error_description=AADSTS70001%3a+Application+'703831e7-1d02-43cf-8209-937a36d97612'+is+not+supported+for+this+API+version.

**Comment by valerijko** [comment]
Few reasons for that:
1. In auth_helper.rb all URLs for oauth2 should have v2.0 after '/common/oauth2/...', for example:
:authorize_url => "/common/oauth2/v2.0/authorize",
                                :token_url => "/common/oauth2/v2.0/token")
2. Also, there should be a scope parameter added:
login_url = client.auth_code.authorize_url(:redirect_uri => authorize_url, :scope => "https://outlook.office.com/calendars.read")
3. And, in the get_token_from_code 'resources' should be removed, scope should be used instead of it:
token = client.auth_code.get_token(auth_code,
                                       :redirect_uri => authorize_url,
                                       :scope => "https://outlook.office.com/calendars.read")

**Comment by jasonjoh** [comment]
Thanks for reporting! I know this doesn't work with the v2 auth model from Azure, it was written for the v1 app model. I will update this eventually to use v2, I just haven't had the time yet :).

**Comment by lievcin** [comment]
Hi @jasonjoh , I'm trying to build an app that allows you to interact with some of the Office365 resources, also getting a failure when trying to run as per instructions. Is this still active?

In my case I'm getting:

`A refresh_token is not available`

**Comment by jasonjoh** [comment]
Yes, this should be active. For a refresh token you need to add the `offline_access` scope to your authorization request.

**Comment by jasonjoh** [comment]
This is resolved by #2
